
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ActionsAction;

	private global::Gtk.Action addEmployee;

	private global::Gtk.Action removeEmployee;

	private global::Gtk.Action quitAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ActionsAction = new global::Gtk.Action("ActionsAction", global::Mono.Unix.Catalog.GetString("Actions"), null, null);
		this.ActionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Actions");
		w1.Add(this.ActionsAction, null);
		this.addEmployee = new global::Gtk.Action("addEmployee", global::Mono.Unix.Catalog.GetString("_Add Employee"), null, "gtk-add");
		this.addEmployee.ShortLabel = global::Mono.Unix.Catalog.GetString("_AddEmployee");
		w1.Add(this.addEmployee, null);
		this.removeEmployee = new global::Gtk.Action("removeEmployee", global::Mono.Unix.Catalog.GetString("_Remove Employee"), null, "gtk-remove");
		this.removeEmployee.ShortLabel = global::Mono.Unix.Catalog.GetString("_RemoveEmployee");
		w1.Add(this.removeEmployee, null);
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
		w1.Add(this.quitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Payroll");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='ActionsAction' action='ActionsAction'><menuitem name='addEmployee' action='addEmployee'/><menuitem name='removeEmployee' action='removeEmployee'/><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w3.Position = 3;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler(this.OnQuitActionActivated);
	}
}
