
// This file has been generated by the GUI designer. Do not modify.
namespace PayrollGTK
{
	public partial class AddEmployee
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Entry empidEntry;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Entry name;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.Entry address;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button cancel;

		private global::Gtk.Button submit;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox8;

		private global::Gtk.VBox vbox8;

		private global::Gtk.RadioButton Hourly;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label5;

		private global::Gtk.Entry hourlyRate;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox3;

		private global::Gtk.RadioButton Salary;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label7;

		private global::Gtk.Entry salaryValue;

		private global::Gtk.HBox hbox7;

		private global::Gtk.RadioButton commision;

		private global::Gtk.VBox vbox7;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label8;

		private global::Gtk.Entry commisionRate;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label9;

		private global::Gtk.Entry commisionSalary;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget PayrollGTK.AddEmployee
			this.Name = "PayrollGTK.AddEmployee";
			this.Title = global::Mono.Unix.Catalog.GetString("AddEmployee");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child PayrollGTK.AddEmployee.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("EmployeeID");
			this.hbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.empidEntry = new global::Gtk.Entry();
			this.empidEntry.CanFocus = true;
			this.empidEntry.Name = "empidEntry";
			this.empidEntry.IsEditable = true;
			this.empidEntry.InvisibleChar = '•';
			this.hbox2.Add(this.empidEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.empidEntry]));
			w2.Position = 1;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.name = new global::Gtk.Entry();
			this.name.CanFocus = true;
			this.name.Name = "name";
			this.name.IsEditable = true;
			this.name.InvisibleChar = '•';
			this.hbox3.Add(this.name);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.name]));
			w5.Position = 1;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Address");
			this.hbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.address = new global::Gtk.Entry();
			this.address.CanFocus = true;
			this.address.Name = "address";
			this.address.IsEditable = true;
			this.address.InvisibleChar = '•';
			this.hbox4.Add(this.address);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.address]));
			w8.Position = 1;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w9.Position = 2;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.cancel = new global::Gtk.Button();
			this.cancel.CanFocus = true;
			this.cancel.Name = "cancel";
			this.cancel.UseUnderline = true;
			this.cancel.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.hbox6.Add(this.cancel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.cancel]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.submit = new global::Gtk.Button();
			this.submit.Sensitive = false;
			this.submit.CanFocus = true;
			this.submit.Name = "submit";
			this.submit.UseUnderline = true;
			this.submit.Label = global::Mono.Unix.Catalog.GetString("Submit");
			this.hbox6.Add(this.submit);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.submit]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox2.Add(this.vbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox6]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.Hourly = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Hourly"));
			this.Hourly.CanFocus = true;
			this.Hourly.Name = "Hourly";
			this.Hourly.Active = false;
			this.Hourly.DrawIndicator = true;
			this.Hourly.UseUnderline = true;
			this.Hourly.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox8.Add(this.Hourly);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.Hourly]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox8.Add(this.vbox8);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox8]));
			w16.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("HourlyRate");
			this.vbox9.Add(this.label5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hourlyRate = new global::Gtk.Entry();
			this.hourlyRate.CanFocus = true;
			this.hourlyRate.Name = "hourlyRate";
			this.hourlyRate.IsEditable = false;
			this.hourlyRate.InvisibleChar = '•';
			this.vbox9.Add(this.hourlyRate);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hourlyRate]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox8.Add(this.vbox9);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox9]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox5.Add(this.hbox8);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.Salary = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Salary"));
			this.Salary.CanFocus = true;
			this.Salary.Name = "Salary";
			this.Salary.Active = false;
			this.Salary.DrawIndicator = true;
			this.Salary.UseUnderline = true;
			this.Salary.Group = this.Hourly.Group;
			this.vbox3.Add(this.Salary);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Salary]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox5.Add(this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
			w22.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Salary");
			this.vbox4.Add(this.label7);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label7]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.salaryValue = new global::Gtk.Entry();
			this.salaryValue.CanFocus = true;
			this.salaryValue.Name = "salaryValue";
			this.salaryValue.IsEditable = true;
			this.salaryValue.InvisibleChar = '•';
			this.vbox4.Add(this.salaryValue);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.salaryValue]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox5.Add(this.vbox4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox4]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.commision = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Commision"));
			this.commision.CanFocus = true;
			this.commision.Name = "commision";
			this.commision.Active = false;
			this.commision.DrawIndicator = true;
			this.commision.UseUnderline = true;
			this.commision.Group = this.Hourly.Group;
			this.hbox7.Add(this.commision);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.commision]));
			w27.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Commision Rate");
			this.vbox10.Add(this.label8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label8]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.commisionRate = new global::Gtk.Entry();
			this.commisionRate.CanFocus = true;
			this.commisionRate.Name = "commisionRate";
			this.commisionRate.IsEditable = true;
			this.commisionRate.InvisibleChar = '•';
			this.vbox10.Add(this.commisionRate);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.commisionRate]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox7.Add(this.vbox10);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox10]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Commision Salary");
			this.vbox11.Add(this.label9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label9]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.commisionSalary = new global::Gtk.Entry();
			this.commisionSalary.CanFocus = true;
			this.commisionSalary.Name = "commisionSalary";
			this.commisionSalary.IsEditable = true;
			this.commisionSalary.InvisibleChar = '•';
			this.vbox11.Add(this.commisionSalary);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.commisionSalary]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox7.Add(this.vbox11);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox11]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox7.Add(this.vbox7);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox7]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox1.Add(this.vbox5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
			w36.Position = 1;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 573;
			this.DefaultHeight = 522;
			this.Show();
			this.empidEntry.Changed += new global::System.EventHandler(this.OnEmpidEntryChanged);
			this.name.Changed += new global::System.EventHandler(this.OnNameChanged);
			this.address.Changed += new global::System.EventHandler(this.OnAddressChanged);
			this.Hourly.Toggled += new global::System.EventHandler(this.OnHourlyToggled);
			this.hourlyRate.Changed += new global::System.EventHandler(this.OnHourlyRateChanged);
			this.Salary.Toggled += new global::System.EventHandler(this.OnSalaryToggled);
			this.salaryValue.Changed += new global::System.EventHandler(this.OnSalaryValueChanged);
			this.commision.Toggled += new global::System.EventHandler(this.OnCommisionToggled);
			this.commisionRate.Changed += new global::System.EventHandler(this.OnCommisionRateChanged);
			this.commisionSalary.Changed += new global::System.EventHandler(this.OnCommisionSalaryChanged);
		}
	}
}
